name: build-only

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]

    name: Build only ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v3

    - name: Build
      run: |
        go build -o ./vsniff ./...
        ls

    # Code signing is necessary so we don't do mac releases from github actions...
