name: build-only

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]

    name: Build only ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v3

    - name: Build
      run: |
        go build -o ./vsniff.exe ./...
        ls

    - name: Upload release (maybe)
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: vsniff.exe
